[about]
## Author / Copyright notice
author=AvenReal

description=An OCR plugin that will do things

## If the plugin is packed with Xournal++, use
## <xournalpp> then it gets the same version number
version=<xournalpp>

[default]
enabled=false

[plugin]
mainfile=main.lua
